#include "lua_native_binding.hpp"
#include "game/rdr/Natives.hpp"

namespace Lua::native
{
	static bool LUA_NATIVE_UITUTORIAL_UITUTORIAL_GET_IS_THREAT_INDICATOR_CAPABLE_RADAR_SHOWN_()
	{
		auto retval = (bool)UITUTORIAL::_UITUTORIAL_GET_IS_THREAT_INDICATOR_CAPABLE_RADAR_SHOWN();
		return retval;
	}

	static bool LUA_NATIVE_UITUTORIAL_UITUTORIAL_GET_IS_THREAT_INDICATOR_ON_()
	{
		auto retval = (bool)UITUTORIAL::_UITUTORIAL_GET_IS_THREAT_INDICATOR_ON();
		return retval;
	}

	static void LUA_NATIVE_UITUTORIAL_UITUTORIAL_SET_RPG_ICON_VISIBILITY_(int rpgIcon, int visibility)
	{
		UITUTORIAL::_UITUTORIAL_SET_RPG_ICON_VISIBILITY(rpgIcon, visibility);
	}

	void init_native_binding_UITUTORIAL(sol::state& L)
	{
		auto UITUTORIAL = L["UITUTORIAL"].get_or_create<sol::table>();
		UITUTORIAL.set_function("UITUTORIAL_GET_IS_THREAT_INDICATOR_CAPABLE_RADAR_SHOWN_", LUA_NATIVE_UITUTORIAL_UITUTORIAL_GET_IS_THREAT_INDICATOR_CAPABLE_RADAR_SHOWN_);
		UITUTORIAL.set_function("UITUTORIAL_GET_IS_THREAT_INDICATOR_ON_", LUA_NATIVE_UITUTORIAL_UITUTORIAL_GET_IS_THREAT_INDICATOR_ON_);
		UITUTORIAL.set_function("UITUTORIAL_SET_RPG_ICON_VISIBILITY_", LUA_NATIVE_UITUTORIAL_UITUTORIAL_SET_RPG_ICON_VISIBILITY_);
	}
}
