#include "lua_native_binding.hpp"
#include "game/rdr/Natives.hpp"

namespace Lua::native
{
	static int LUA_NATIVE_UISTICKYFEED_UI_STICKY_FEED_CREATE_ERROR_MESSAGE_(uintptr_t p0, uintptr_t p1, bool p2)
	{
		auto retval = UISTICKYFEED::_UI_STICKY_FEED_CREATE_ERROR_MESSAGE((Any*)p0, (Any*)p1, p2);
		return retval;
	}

	static int LUA_NATIVE_UISTICKYFEED_UI_STICKY_FEED_CREATE_DEATH_FAIL_MESSAGE_(uintptr_t p0, uintptr_t p1, bool p2)
	{
		auto retval = UISTICKYFEED::_UI_STICKY_FEED_CREATE_DEATH_FAIL_MESSAGE((Any*)p0, (Any*)p1, p2);
		return retval;
	}

	static int LUA_NATIVE_UISTICKYFEED_UI_STICKY_FEED_CREATE_WARNING_MESSAGE_(uintptr_t p0, uintptr_t p1, bool p2)
	{
		auto retval = UISTICKYFEED::_UI_STICKY_FEED_CREATE_WARNING_MESSAGE((Any*)p0, (Any*)p1, p2);
		return retval;
	}

	static void LUA_NATIVE_UISTICKYFEED_UI_STICKY_FEED_UPDATE_MESSAGE_(int msgId, uintptr_t p1, bool p2)
	{
		UISTICKYFEED::_UI_STICKY_FEED_UPDATE_MESSAGE(msgId, (Any*)p1, p2);
	}

	static void LUA_NATIVE_UISTICKYFEED_UI_STICKY_FEED_CLEAR_MESSAGE_(int msgId)
	{
		UISTICKYFEED::_UI_STICKY_FEED_CLEAR_MESSAGE(msgId);
	}

	static bool LUA_NATIVE_UISTICKYFEED_UI_STICKY_FEED_IS_CHANNEL_ACTIVE_(int stickyFeedChannel)
	{
		auto retval = (bool)UISTICKYFEED::_UI_STICKY_FEED_IS_CHANNEL_ACTIVE(stickyFeedChannel);
		return retval;
	}

	static bool LUA_NATIVE_UISTICKYFEED_UI_STICKY_FEED_IS_ALERT_SCREEN_ACTIVE_()
	{
		auto retval = (bool)UISTICKYFEED::_UI_STICKY_FEED_IS_ALERT_SCREEN_ACTIVE();
		return retval;
	}

	static int LUA_NATIVE_UISTICKYFEED_UI_STICKY_FEED_GET_MESSAGE_STATE_(int msgId)
	{
		auto retval = UISTICKYFEED::_UI_STICKY_FEED_GET_MESSAGE_STATE(msgId);
		return retval;
	}

	void init_native_binding_UISTICKYFEED(sol::state& L)
	{
		auto UISTICKYFEED = L["UISTICKYFEED"].get_or_create<sol::table>();
		UISTICKYFEED.set_function("UI_STICKY_FEED_CREATE_ERROR_MESSAGE_", LUA_NATIVE_UISTICKYFEED_UI_STICKY_FEED_CREATE_ERROR_MESSAGE_);
		UISTICKYFEED.set_function("UI_STICKY_FEED_CREATE_DEATH_FAIL_MESSAGE_", LUA_NATIVE_UISTICKYFEED_UI_STICKY_FEED_CREATE_DEATH_FAIL_MESSAGE_);
		UISTICKYFEED.set_function("UI_STICKY_FEED_CREATE_WARNING_MESSAGE_", LUA_NATIVE_UISTICKYFEED_UI_STICKY_FEED_CREATE_WARNING_MESSAGE_);
		UISTICKYFEED.set_function("UI_STICKY_FEED_UPDATE_MESSAGE_", LUA_NATIVE_UISTICKYFEED_UI_STICKY_FEED_UPDATE_MESSAGE_);
		UISTICKYFEED.set_function("UI_STICKY_FEED_CLEAR_MESSAGE_", LUA_NATIVE_UISTICKYFEED_UI_STICKY_FEED_CLEAR_MESSAGE_);
		UISTICKYFEED.set_function("UI_STICKY_FEED_IS_CHANNEL_ACTIVE_", LUA_NATIVE_UISTICKYFEED_UI_STICKY_FEED_IS_CHANNEL_ACTIVE_);
		UISTICKYFEED.set_function("UI_STICKY_FEED_IS_ALERT_SCREEN_ACTIVE_", LUA_NATIVE_UISTICKYFEED_UI_STICKY_FEED_IS_ALERT_SCREEN_ACTIVE_);
		UISTICKYFEED.set_function("UI_STICKY_FEED_GET_MESSAGE_STATE_", LUA_NATIVE_UISTICKYFEED_UI_STICKY_FEED_GET_MESSAGE_STATE_);
	}
}
