#include "lua_native_binding.hpp"
#include "game/rdr/Natives.hpp"

namespace Lua::native
{
	static Entity LUA_NATIVE_AICOVERPOINT_0x53E4D0C079CA6855_(ScrHandle handle)
	{
		auto retval = AICOVERPOINT::_0x53E4D0C079CA6855(handle);
		return retval;
	}

	static bool LUA_NATIVE_AICOVERPOINT_DOES_COVER_POINT_EXIST_(ScrHandle handle)
	{
		auto retval = (bool)AICOVERPOINT::_DOES_COVER_POINT_EXIST(handle);
		return retval;
	}

	static int LUA_NATIVE_AICOVERPOINT_GET_COVER_POINT_STATE_FROM_PED_(Ped ped)
	{
		auto retval = AICOVERPOINT::_GET_COVER_POINT_STATE_FROM_PED(ped);
		return retval;
	}

	static void LUA_NATIVE_AICOVERPOINT_TASK_ENTER_COVER(Ped ped)
	{
		AICOVERPOINT::TASK_ENTER_COVER(ped);
	}

	static void LUA_NATIVE_AICOVERPOINT_TASK_EXIT_COVER(Ped ped)
	{
		AICOVERPOINT::TASK_EXIT_COVER(ped);
	}

	static int LUA_NATIVE_AICOVERPOINT_0x957D7E750216D74B_(Ped ped)
	{
		auto retval = AICOVERPOINT::_0x957D7E750216D74B(ped);
		return retval;
	}

	static void LUA_NATIVE_AICOVERPOINT_TASK_AI_SEEK_COVER_TO_COVER_POINT_(uintptr_t args)
	{
		AICOVERPOINT::_TASK_AI_SEEK_COVER_TO_COVER_POINT((Any*)args);
	}

	static void LUA_NATIVE_AICOVERPOINT_0x64340DC208D671D5_(sol::stack_object coverLayer)
	{
		AICOVERPOINT::_0x64340DC208D671D5(coverLayer.is<const char*>() ? coverLayer.as<const char*>() : nullptr);
	}

	static void LUA_NATIVE_AICOVERPOINT_0x7A1FDCF35EAA140F_(sol::stack_object coverLayer)
	{
		AICOVERPOINT::_0x7A1FDCF35EAA140F(coverLayer.is<const char*>() ? coverLayer.as<const char*>() : nullptr);
	}

	static void LUA_NATIVE_AICOVERPOINT_REQUEST_FLINCH_COVER_ANIM_(Ped ped)
	{
		AICOVERPOINT::_REQUEST_FLINCH_COVER_ANIM(ped);
	}

	static void LUA_NATIVE_AICOVERPOINT_0x3C7A9C2C953128FE_(Ped ped)
	{
		AICOVERPOINT::_0x3C7A9C2C953128FE(ped);
	}

	static void LUA_NATIVE_AICOVERPOINT_0xEBA51A294C73292E_(uintptr_t args)
	{
		AICOVERPOINT::_0xEBA51A294C73292E((Any*)args);
	}

	static void LUA_NATIVE_AICOVERPOINT_0x140B3CB1D424A945_(Ped ped, Hash weaponHash)
	{
		AICOVERPOINT::_0x140B3CB1D424A945(ped, weaponHash);
	}

	static bool LUA_NATIVE_AICOVERPOINT_ARE_LOAD_COVER_ANIMS_LOADED_(Ped ped)
	{
		auto retval = (bool)AICOVERPOINT::_ARE_LOAD_COVER_ANIMS_LOADED(ped);
		return retval;
	}

	static void LUA_NATIVE_AICOVERPOINT_STOP_RUNNING_COVER_ANIMS_(Ped ped)
	{
		AICOVERPOINT::_STOP_RUNNING_COVER_ANIMS(ped);
	}

	static void LUA_NATIVE_AICOVERPOINT_0x733077295AB51304_(uintptr_t args)
	{
		AICOVERPOINT::_0x733077295AB51304((Any*)args);
	}

	static ScrHandle LUA_NATIVE_AICOVERPOINT_ADD_SCRIPTED_COVER_POINT_(uintptr_t data)
	{
		auto retval = AICOVERPOINT::_ADD_SCRIPTED_COVER_POINT((Any*)data);
		return retval;
	}

	void init_native_binding_AICOVERPOINT(sol::state& L)
	{
		auto AICOVERPOINT = L["AICOVERPOINT"].get_or_create<sol::table>();
		AICOVERPOINT.set_function("0x53E4D0C079CA6855_", LUA_NATIVE_AICOVERPOINT_0x53E4D0C079CA6855_);
		AICOVERPOINT.set_function("DOES_COVER_POINT_EXIST_", LUA_NATIVE_AICOVERPOINT_DOES_COVER_POINT_EXIST_);
		AICOVERPOINT.set_function("GET_COVER_POINT_STATE_FROM_PED_", LUA_NATIVE_AICOVERPOINT_GET_COVER_POINT_STATE_FROM_PED_);
		AICOVERPOINT.set_function("TASK_ENTER_COVER", LUA_NATIVE_AICOVERPOINT_TASK_ENTER_COVER);
		AICOVERPOINT.set_function("TASK_EXIT_COVER", LUA_NATIVE_AICOVERPOINT_TASK_EXIT_COVER);
		AICOVERPOINT.set_function("0x957D7E750216D74B_", LUA_NATIVE_AICOVERPOINT_0x957D7E750216D74B_);
		AICOVERPOINT.set_function("TASK_AI_SEEK_COVER_TO_COVER_POINT_", LUA_NATIVE_AICOVERPOINT_TASK_AI_SEEK_COVER_TO_COVER_POINT_);
		AICOVERPOINT.set_function("0x64340DC208D671D5_", LUA_NATIVE_AICOVERPOINT_0x64340DC208D671D5_);
		AICOVERPOINT.set_function("0x7A1FDCF35EAA140F_", LUA_NATIVE_AICOVERPOINT_0x7A1FDCF35EAA140F_);
		AICOVERPOINT.set_function("REQUEST_FLINCH_COVER_ANIM_", LUA_NATIVE_AICOVERPOINT_REQUEST_FLINCH_COVER_ANIM_);
		AICOVERPOINT.set_function("0x3C7A9C2C953128FE_", LUA_NATIVE_AICOVERPOINT_0x3C7A9C2C953128FE_);
		AICOVERPOINT.set_function("0xEBA51A294C73292E_", LUA_NATIVE_AICOVERPOINT_0xEBA51A294C73292E_);
		AICOVERPOINT.set_function("0x140B3CB1D424A945_", LUA_NATIVE_AICOVERPOINT_0x140B3CB1D424A945_);
		AICOVERPOINT.set_function("ARE_LOAD_COVER_ANIMS_LOADED_", LUA_NATIVE_AICOVERPOINT_ARE_LOAD_COVER_ANIMS_LOADED_);
		AICOVERPOINT.set_function("STOP_RUNNING_COVER_ANIMS_", LUA_NATIVE_AICOVERPOINT_STOP_RUNNING_COVER_ANIMS_);
		AICOVERPOINT.set_function("0x733077295AB51304_", LUA_NATIVE_AICOVERPOINT_0x733077295AB51304_);
		AICOVERPOINT.set_function("ADD_SCRIPTED_COVER_POINT_", LUA_NATIVE_AICOVERPOINT_ADD_SCRIPTED_COVER_POINT_);
	}
}
