#include "lua_native_binding.hpp"
#include "game/rdr/Natives.hpp"

namespace Lua::native
{
	static bool LUA_NATIVE_SPACTIONPROXY_SPACTIONPROXY_START_MANAGER_()
	{
		auto retval = (bool)SPACTIONPROXY::_SPACTIONPROXY_START_MANAGER();
		return retval;
	}

	static bool LUA_NATIVE_SPACTIONPROXY_SPACTIONPROXY_MANAGER_IS_READY_()
	{
		auto retval = (bool)SPACTIONPROXY::_SPACTIONPROXY_MANAGER_IS_READY();
		return retval;
	}

	static bool LUA_NATIVE_SPACTIONPROXY_SPACTIONPROXY_MANAGER_IS_FAILED_()
	{
		auto retval = (bool)SPACTIONPROXY::_SPACTIONPROXY_MANAGER_IS_FAILED();
		return retval;
	}

	static bool LUA_NATIVE_SPACTIONPROXY_SPACTIONPROXY_GET_NEXT_PENDING_CRAFTING_ACTION_(uintptr_t data)
	{
		auto retval = (bool)SPACTIONPROXY::_SPACTIONPROXY_GET_NEXT_PENDING_CRAFTING_ACTION((Any*)data);
		return retval;
	}

	static bool LUA_NATIVE_SPACTIONPROXY_SPACTIONPROXY_GET_NEXT_PENDING_BUY_ACTION_(uintptr_t data)
	{
		auto retval = (bool)SPACTIONPROXY::_SPACTIONPROXY_GET_NEXT_PENDING_BUY_ACTION((Any*)data);
		return retval;
	}

	static bool LUA_NATIVE_SPACTIONPROXY_SPACTIONPROXY_PROCESS_ACTION_(Any p0, bool p1)
	{
		auto retval = (bool)SPACTIONPROXY::_SPACTIONPROXY_PROCESS_ACTION(p0, p1);
		return retval;
	}

	void init_native_binding_SPACTIONPROXY(sol::state& L)
	{
		auto SPACTIONPROXY = L["SPACTIONPROXY"].get_or_create<sol::table>();
		SPACTIONPROXY.set_function("SPACTIONPROXY_START_MANAGER_", LUA_NATIVE_SPACTIONPROXY_SPACTIONPROXY_START_MANAGER_);
		SPACTIONPROXY.set_function("SPACTIONPROXY_MANAGER_IS_READY_", LUA_NATIVE_SPACTIONPROXY_SPACTIONPROXY_MANAGER_IS_READY_);
		SPACTIONPROXY.set_function("SPACTIONPROXY_MANAGER_IS_FAILED_", LUA_NATIVE_SPACTIONPROXY_SPACTIONPROXY_MANAGER_IS_FAILED_);
		SPACTIONPROXY.set_function("SPACTIONPROXY_GET_NEXT_PENDING_CRAFTING_ACTION_", LUA_NATIVE_SPACTIONPROXY_SPACTIONPROXY_GET_NEXT_PENDING_CRAFTING_ACTION_);
		SPACTIONPROXY.set_function("SPACTIONPROXY_GET_NEXT_PENDING_BUY_ACTION_", LUA_NATIVE_SPACTIONPROXY_SPACTIONPROXY_GET_NEXT_PENDING_BUY_ACTION_);
		SPACTIONPROXY.set_function("SPACTIONPROXY_PROCESS_ACTION_", LUA_NATIVE_SPACTIONPROXY_SPACTIONPROXY_PROCESS_ACTION_);
	}
}
