#include "lua_native_binding.hpp"
#include "game/rdr/Natives.hpp"

namespace Lua::native
{
	static std::tuple<bool, int, int> LUA_NATIVE_NETSHOPPING_CASHINVENTORY_INIT_SESSION_STATUS(int p0, int p1)
	{
		std::tuple<bool, int, int> return_values;
		std::get<0>(return_values) = (bool)NETSHOPPING::CASHINVENTORY_INIT_SESSION_STATUS(&p0, &p1);
		std::get<1>(return_values) = p0;
		std::get<2>(return_values) = p1;

		return return_values;
	}

	static bool LUA_NATIVE_NETSHOPPING_CASHINVENTORY_IS_SESSION_READY_()
	{
		auto retval = (bool)NETSHOPPING::_CASHINVENTORY_IS_SESSION_READY();
		return retval;
	}

	static bool LUA_NATIVE_NETSHOPPING_CASHINVENTORY_IS_CONNECTION_FAULTED()
	{
		auto retval = (bool)NETSHOPPING::CASHINVENTORY_IS_CONNECTION_FAULTED();
		return retval;
	}

	static bool LUA_NATIVE_NETSHOPPING_CASHINVENTORY_INIT_SESSION_IS_FAULTED_()
	{
		auto retval = (bool)NETSHOPPING::_CASHINVENTORY_INIT_SESSION_IS_FAULTED();
		return retval;
	}

	static std::tuple<bool, int> LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_FIRE_AND_FORGET_ITEM_(Hash actionHash, int id, uintptr_t item, int p3)
	{
		std::tuple<bool, int> return_values;
		std::get<0>(return_values) = (bool)NETSHOPPING::_CASHINVENTORY_TRANSACTION_FIRE_AND_FORGET_ITEM(actionHash, &id, (Any*)item, p3);
		std::get<1>(return_values) = id;

		return return_values;
	}

	static std::tuple<bool, int> LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_START_(int id, Hash type, Hash actionHash)
	{
		std::tuple<bool, int> return_values;
		std::get<0>(return_values) = (bool)NETSHOPPING::_CASHINVENTORY_TRANSACTION_START(&id, type, actionHash);
		std::get<1>(return_values) = id;

		return return_values;
	}

	static bool LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_GET_BASKET_IS_VALID_(int id)
	{
		auto retval = (bool)NETSHOPPING::_CASHINVENTORY_TRANSACTION_GET_BASKET_IS_VALID(id);
		return retval;
	}

	static bool LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_DELETE_(int id)
	{
		auto retval = (bool)NETSHOPPING::_CASHINVENTORY_TRANSACTION_DELETE(id);
		return retval;
	}

	static int LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_VALIDATE_ITEM_(Hash p0, uintptr_t p1)
	{
		auto retval = NETSHOPPING::_CASHINVENTORY_TRANSACTION_VALIDATE_ITEM(p0, (Any*)p1);
		return retval;
	}

	static int LUA_NATIVE_NETSHOPPING_0x38640A8C2DEF011B_(int p0)
	{
		auto retval = NETSHOPPING::_0x38640A8C2DEF011B(p0);
		return retval;
	}

	static bool LUA_NATIVE_NETSHOPPING_0xA3B8D31C13CB4239_(int p0, Hash p1, uintptr_t p2, int p3, uintptr_t p4, int p5)
	{
		auto retval = (bool)NETSHOPPING::_0xA3B8D31C13CB4239(p0, p1, (Any*)p2, p3, (Any*)p4, p5);
		return retval;
	}

	static bool LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_ADD_AWARD_(int id, Hash hash, uintptr_t p2, uintptr_t p3)
	{
		auto retval = (bool)NETSHOPPING::_CASHINVENTORY_TRANSACTION_ADD_AWARD(id, hash, (Any*)p2, (Any*)p3);
		return retval;
	}

	static bool LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_GET_ITEM_INFO_(int id, int index, uintptr_t itemInfo)
	{
		auto retval = (bool)NETSHOPPING::_CASHINVENTORY_TRANSACTION_GET_ITEM_INFO(id, index, (Any*)itemInfo);
		return retval;
	}

	static int LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_GET_NUM_OF_ITEMS_(int id)
	{
		auto retval = NETSHOPPING::_CASHINVENTORY_TRANSACTION_GET_NUM_OF_ITEMS(id);
		return retval;
	}

	static Hash LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_GET_ACTION_(int id)
	{
		auto retval = NETSHOPPING::_CASHINVENTORY_TRANSACTION_GET_ACTION(id);
		return retval;
	}

	static bool LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_CHECKOUT_(int id)
	{
		auto retval = (bool)NETSHOPPING::_CASHINVENTORY_TRANSACTION_CHECKOUT(id);
		return retval;
	}

	static std::tuple<bool, int> LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_CHECKOUT_STATUS_(int id, int status)
	{
		std::tuple<bool, int> return_values;
		std::get<0>(return_values) = (bool)NETSHOPPING::_CASHINVENTORY_TRANSACTION_CHECKOUT_STATUS(id, &status);
		std::get<1>(return_values) = status;

		return return_values;
	}

	static int LUA_NATIVE_NETSHOPPING_0xB6F4557060EF0FB4_(int p0, int p1)
	{
		auto retval = NETSHOPPING::_0xB6F4557060EF0FB4(p0, p1);
		return retval;
	}

	static bool LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_RESPONSE_GET_ITEM_INFO_(int id, int index, uintptr_t itemInfo)
	{
		auto retval = (bool)NETSHOPPING::_CASHINVENTORY_TRANSACTION_RESPONSE_GET_ITEM_INFO(id, index, (Any*)itemInfo);
		return retval;
	}

	static bool LUA_NATIVE_NETSHOPPING_0xCE54C9ABE6FBC6DB_(Hash p0)
	{
		auto retval = (bool)NETSHOPPING::_0xCE54C9ABE6FBC6DB(p0);
		return retval;
	}

	static bool LUA_NATIVE_NETSHOPPING_0xA0B7094629724974_(Hash p0, Any p1)
	{
		auto retval = (bool)NETSHOPPING::_0xA0B7094629724974(p0, p1);
		return retval;
	}

	static bool LUA_NATIVE_NETSHOPPING_0x92A32BA29622763F_(int id, int index, uintptr_t p2)
	{
		auto retval = (bool)NETSHOPPING::_0x92A32BA29622763F(id, index, (Any*)p2);
		return retval;
	}

	static bool LUA_NATIVE_NETSHOPPING_0x3FA09DD57B93C0DE_(Hash p0, int p1, int p2, Any p3, int p4)
	{
		auto retval = (bool)NETSHOPPING::_0x3FA09DD57B93C0DE(p0, p1, p2, p3, p4);
		return retval;
	}

	static bool LUA_NATIVE_NETSHOPPING_0xD1555FBC96C88444_(Hash p0, int p1, int p2, Any p3, int p4)
	{
		auto retval = (bool)NETSHOPPING::_0xD1555FBC96C88444(p0, p1, p2, p3, p4);
		return retval;
	}

	void init_native_binding_NETSHOPPING(sol::state& L)
	{
		auto NETSHOPPING = L["NETSHOPPING"].get_or_create<sol::table>();
		NETSHOPPING.set_function("CASHINVENTORY_INIT_SESSION_STATUS", LUA_NATIVE_NETSHOPPING_CASHINVENTORY_INIT_SESSION_STATUS);
		NETSHOPPING.set_function("CASHINVENTORY_IS_SESSION_READY_", LUA_NATIVE_NETSHOPPING_CASHINVENTORY_IS_SESSION_READY_);
		NETSHOPPING.set_function("CASHINVENTORY_IS_CONNECTION_FAULTED", LUA_NATIVE_NETSHOPPING_CASHINVENTORY_IS_CONNECTION_FAULTED);
		NETSHOPPING.set_function("CASHINVENTORY_INIT_SESSION_IS_FAULTED_", LUA_NATIVE_NETSHOPPING_CASHINVENTORY_INIT_SESSION_IS_FAULTED_);
		NETSHOPPING.set_function("CASHINVENTORY_TRANSACTION_FIRE_AND_FORGET_ITEM_", LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_FIRE_AND_FORGET_ITEM_);
		NETSHOPPING.set_function("CASHINVENTORY_TRANSACTION_START_", LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_START_);
		NETSHOPPING.set_function("CASHINVENTORY_TRANSACTION_GET_BASKET_IS_VALID_", LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_GET_BASKET_IS_VALID_);
		NETSHOPPING.set_function("CASHINVENTORY_TRANSACTION_DELETE_", LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_DELETE_);
		NETSHOPPING.set_function("CASHINVENTORY_TRANSACTION_VALIDATE_ITEM_", LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_VALIDATE_ITEM_);
		NETSHOPPING.set_function("0x38640A8C2DEF011B_", LUA_NATIVE_NETSHOPPING_0x38640A8C2DEF011B_);
		NETSHOPPING.set_function("0xA3B8D31C13CB4239_", LUA_NATIVE_NETSHOPPING_0xA3B8D31C13CB4239_);
		NETSHOPPING.set_function("CASHINVENTORY_TRANSACTION_ADD_AWARD_", LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_ADD_AWARD_);
		NETSHOPPING.set_function("CASHINVENTORY_TRANSACTION_GET_ITEM_INFO_", LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_GET_ITEM_INFO_);
		NETSHOPPING.set_function("CASHINVENTORY_TRANSACTION_GET_NUM_OF_ITEMS_", LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_GET_NUM_OF_ITEMS_);
		NETSHOPPING.set_function("CASHINVENTORY_TRANSACTION_GET_ACTION_", LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_GET_ACTION_);
		NETSHOPPING.set_function("CASHINVENTORY_TRANSACTION_CHECKOUT_", LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_CHECKOUT_);
		NETSHOPPING.set_function("CASHINVENTORY_TRANSACTION_CHECKOUT_STATUS_", LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_CHECKOUT_STATUS_);
		NETSHOPPING.set_function("0xB6F4557060EF0FB4_", LUA_NATIVE_NETSHOPPING_0xB6F4557060EF0FB4_);
		NETSHOPPING.set_function("CASHINVENTORY_TRANSACTION_RESPONSE_GET_ITEM_INFO_", LUA_NATIVE_NETSHOPPING_CASHINVENTORY_TRANSACTION_RESPONSE_GET_ITEM_INFO_);
		NETSHOPPING.set_function("0xCE54C9ABE6FBC6DB_", LUA_NATIVE_NETSHOPPING_0xCE54C9ABE6FBC6DB_);
		NETSHOPPING.set_function("0xA0B7094629724974_", LUA_NATIVE_NETSHOPPING_0xA0B7094629724974_);
		NETSHOPPING.set_function("0x92A32BA29622763F_", LUA_NATIVE_NETSHOPPING_0x92A32BA29622763F_);
		NETSHOPPING.set_function("0x3FA09DD57B93C0DE_", LUA_NATIVE_NETSHOPPING_0x3FA09DD57B93C0DE_);
		NETSHOPPING.set_function("0xD1555FBC96C88444_", LUA_NATIVE_NETSHOPPING_0xD1555FBC96C88444_);
	}
}
