#include "lua_native_binding.hpp"
#include "game/rdr/Natives.hpp"

namespace Lua::native
{
	static void LUA_NATIVE_INTERACTION_SET_MOUSE_CURSOR_THIS_FRAME()
	{
		INTERACTION::SET_MOUSE_CURSOR_THIS_FRAME();
	}

	static void LUA_NATIVE_INTERACTION_SET_MOUSE_CURSOR_STYLE(int style)
	{
		INTERACTION::SET_MOUSE_CURSOR_STYLE(style);
	}

	static void LUA_NATIVE_INTERACTION_SET_ALLOW_FIRST_PERSON_MOUSE_CAMERA_MOVEMENT_()
	{
		INTERACTION::_SET_ALLOW_FIRST_PERSON_MOUSE_CAMERA_MOVEMENT();
	}

	static bool LUA_NATIVE_INTERACTION_POINTER_IS_BEING_MOVED_()
	{
		auto retval = (bool)INTERACTION::_POINTER_IS_BEING_MOVED();
		return retval;
	}

	static bool LUA_NATIVE_INTERACTION_POINTER_IS_LEFT_BUTTON_HELD_()
	{
		auto retval = (bool)INTERACTION::_POINTER_IS_LEFT_BUTTON_HELD();
		return retval;
	}

	static bool LUA_NATIVE_INTERACTION_POINTER_IS_LEFT_BUTTON_JUST_RELEASED_()
	{
		auto retval = (bool)INTERACTION::_POINTER_IS_LEFT_BUTTON_JUST_RELEASED();
		return retval;
	}

	void init_native_binding_INTERACTION(sol::state& L)
	{
		auto INTERACTION = L["INTERACTION"].get_or_create<sol::table>();
		INTERACTION.set_function("SET_MOUSE_CURSOR_THIS_FRAME", LUA_NATIVE_INTERACTION_SET_MOUSE_CURSOR_THIS_FRAME);
		INTERACTION.set_function("SET_MOUSE_CURSOR_STYLE", LUA_NATIVE_INTERACTION_SET_MOUSE_CURSOR_STYLE);
		INTERACTION.set_function("SET_ALLOW_FIRST_PERSON_MOUSE_CAMERA_MOVEMENT_", LUA_NATIVE_INTERACTION_SET_ALLOW_FIRST_PERSON_MOUSE_CAMERA_MOVEMENT_);
		INTERACTION.set_function("POINTER_IS_BEING_MOVED_", LUA_NATIVE_INTERACTION_POINTER_IS_BEING_MOVED_);
		INTERACTION.set_function("POINTER_IS_LEFT_BUTTON_HELD_", LUA_NATIVE_INTERACTION_POINTER_IS_LEFT_BUTTON_HELD_);
		INTERACTION.set_function("POINTER_IS_LEFT_BUTTON_JUST_RELEASED_", LUA_NATIVE_INTERACTION_POINTER_IS_LEFT_BUTTON_JUST_RELEASED_);
	}
}
