#include "lua_native_binding.hpp"
#include "game/rdr/Natives.hpp"

namespace Lua::native
{
	static int LUA_NATIVE_POPULATION_GET_NUM_MODELS_IN_POPULATION_SET(Hash popSetHash)
	{
		auto retval = POPULATION::GET_NUM_MODELS_IN_POPULATION_SET(popSetHash);
		return retval;
	}

	static Hash LUA_NATIVE_POPULATION_GET_PED_MODEL_NAME_IN_POPULATION_SET(Hash popSetHash, int index)
	{
		auto retval = POPULATION::GET_PED_MODEL_NAME_IN_POPULATION_SET(popSetHash, index);
		return retval;
	}

	static Hash LUA_NATIVE_POPULATION_GET_RANDOM_MODEL_FROM_POPULATION_SET(Hash popSetHash, int flags, Hash p2, bool p3, bool p4, float x, float y, float z)
	{
		auto retval = POPULATION::GET_RANDOM_MODEL_FROM_POPULATION_SET(popSetHash, flags, p2, p3, p4, x, y, z);
		return retval;
	}

	static PopZone LUA_NATIVE_POPULATION_CREATE_POPZONE_FROM_VOLUME_(Volume volume)
	{
		auto retval = POPULATION::_CREATE_POPZONE_FROM_VOLUME(volume);
		return retval;
	}

	static void LUA_NATIVE_POPULATION_DELETE_SCRIPT_POPZONE_(PopZone popZone)
	{
		POPULATION::_DELETE_SCRIPT_POPZONE(popZone);
	}

	static bool LUA_NATIVE_POPULATION_IS_POPZONE_VALID_(PopZone popZone)
	{
		auto retval = (bool)POPULATION::_IS_POPZONE_VALID(popZone);
		return retval;
	}

	static void LUA_NATIVE_POPULATION_SET_POPZONE_POPULATION_SET(PopZone popZone, Hash populationSetHash)
	{
		POPULATION::SET_POPZONE_POPULATION_SET(popZone, populationSetHash);
	}

	static void LUA_NATIVE_POPULATION_0x7E6BC0B94F5928F0_(PopZone popZone, int p1, int p2)
	{
		POPULATION::_0x7E6BC0B94F5928F0(popZone, p1, p2);
	}

	static void LUA_NATIVE_POPULATION_0x578E2FA64E847C60_(PopZone popZone, int p1)
	{
		POPULATION::_0x578E2FA64E847C60(popZone, p1);
	}

	static void LUA_NATIVE_POPULATION_0x08892122769770D5_(PopZone popZone, bool p1)
	{
		POPULATION::_0x08892122769770D5(popZone, p1);
	}

	static void LUA_NATIVE_POPULATION_0x0F1861101C9A9944_(PopZone popZone, bool p1)
	{
		POPULATION::_0x0F1861101C9A9944(popZone, p1);
	}

	static void LUA_NATIVE_POPULATION_SET_SPAWNER_INFO_PRIORITY(Hash p0, Hash p1, int priority)
	{
		POPULATION::SET_SPAWNER_INFO_PRIORITY(p0, p1, priority);
	}

	static void LUA_NATIVE_POPULATION_CLEAR_SPAWNER_INFO_PRIORITY(Hash p0, Hash p1)
	{
		POPULATION::CLEAR_SPAWNER_INFO_PRIORITY(p0, p1);
	}

	static void LUA_NATIVE_POPULATION_0x638FCFC6042A9473_(Any p0, Any p1)
	{
		POPULATION::_0x638FCFC6042A9473(p0, p1);
	}

	static void LUA_NATIVE_POPULATION_ADD_AMBIENT_AVOIDANCE_RESTRICTION_(Volume volume, int includeFlags, int excludeFlags, Hash p3, Hash p4, Hash p5, int p6)
	{
		POPULATION::_ADD_AMBIENT_AVOIDANCE_RESTRICTION(volume, includeFlags, excludeFlags, p3, p4, p5, p6);
	}

	static void LUA_NATIVE_POPULATION_REMOVE_AMBIENT_AVOIDANCE_RESTRICTION_(Volume volume)
	{
		POPULATION::_REMOVE_AMBIENT_AVOIDANCE_RESTRICTION(volume);
	}

	static void LUA_NATIVE_POPULATION_ADD_AMBIENT_SPAWN_RESTRICTION_(Volume volume, int includeFlags, int excludeFlags, Hash p3, Hash p4, Hash p5, int p6)
	{
		POPULATION::_ADD_AMBIENT_SPAWN_RESTRICTION(volume, includeFlags, excludeFlags, p3, p4, p5, p6);
	}

	static void LUA_NATIVE_POPULATION_REMOVE_AMBIENT_SPAWN_RESTRICTION_(Volume volume)
	{
		POPULATION::_REMOVE_AMBIENT_SPAWN_RESTRICTION(volume);
	}

	static void LUA_NATIVE_POPULATION_0x2161278C6322F740_(int includeFlags, int excludeFlags, int p2, Hash p3, int p4, Volume volume)
	{
		POPULATION::_0x2161278C6322F740(includeFlags, excludeFlags, p2, p3, p4, volume);
	}

	static void LUA_NATIVE_POPULATION_0xF45E46DEECF7DF6E_(int bitFlag, Any p1, Any p2, Any p3, Any p4)
	{
		POPULATION::_0xF45E46DEECF7DF6E(bitFlag, p1, p2, p3, p4);
	}

	static void LUA_NATIVE_POPULATION_0x8EC7CD701F872F87_(Any p0, Any p1, Any p2, Any p3, Any p4, Any p5)
	{
		POPULATION::_0x8EC7CD701F872F87(p0, p1, p2, p3, p4, p5);
	}

	static void LUA_NATIVE_POPULATION_0xC4533E3E87125C9E_(Any p0)
	{
		POPULATION::_0xC4533E3E87125C9E(p0);
	}

	static void LUA_NATIVE_POPULATION_SET_PED_SHOULD_IGNORE_AVOIDANCE_VOLUMES_(Ped ped, int p1)
	{
		POPULATION::_SET_PED_SHOULD_IGNORE_AVOIDANCE_VOLUMES(ped, p1);
	}

	static void LUA_NATIVE_POPULATION_0xDBBF12EA7C1029B2_(Any p0, Any p1)
	{
		POPULATION::_0xDBBF12EA7C1029B2(p0, p1);
	}

	static void LUA_NATIVE_POPULATION_0x247F86595D396344_(Any p0)
	{
		POPULATION::_0x247F86595D396344(p0);
	}

	static void LUA_NATIVE_POPULATION_0x324AB2A68AD8AEE5_()
	{
		POPULATION::_0x324AB2A68AD8AEE5();
	}

	static void LUA_NATIVE_POPULATION_DISABLE_AMBIENT_ROAD_POPULATION(bool unk)
	{
		POPULATION::DISABLE_AMBIENT_ROAD_POPULATION(unk);
	}

	static void LUA_NATIVE_POPULATION_ENABLE_AMBIENT_ROAD_POPULATION()
	{
		POPULATION::ENABLE_AMBIENT_ROAD_POPULATION();
	}

	static void LUA_NATIVE_POPULATION_0x2660E7720EDC4BD0_(Any p0, Any p1, Any p2)
	{
		POPULATION::_0x2660E7720EDC4BD0(p0, p1, p2);
	}

	static Hash LUA_NATIVE_POPULATION_GET_RANDOM_FISH_TYPE_FOR_LOCATION_()
	{
		auto retval = POPULATION::_GET_RANDOM_FISH_TYPE_FOR_LOCATION();
		return retval;
	}

	static void LUA_NATIVE_POPULATION_0xEC116EDB683AD479_(bool p0)
	{
		POPULATION::_0xEC116EDB683AD479(p0);
	}

	void init_native_binding_POPULATION(sol::state& L)
	{
		auto POPULATION = L["POPULATION"].get_or_create<sol::table>();
		POPULATION.set_function("GET_NUM_MODELS_IN_POPULATION_SET", LUA_NATIVE_POPULATION_GET_NUM_MODELS_IN_POPULATION_SET);
		POPULATION.set_function("GET_PED_MODEL_NAME_IN_POPULATION_SET", LUA_NATIVE_POPULATION_GET_PED_MODEL_NAME_IN_POPULATION_SET);
		POPULATION.set_function("GET_RANDOM_MODEL_FROM_POPULATION_SET", LUA_NATIVE_POPULATION_GET_RANDOM_MODEL_FROM_POPULATION_SET);
		POPULATION.set_function("CREATE_POPZONE_FROM_VOLUME_", LUA_NATIVE_POPULATION_CREATE_POPZONE_FROM_VOLUME_);
		POPULATION.set_function("DELETE_SCRIPT_POPZONE_", LUA_NATIVE_POPULATION_DELETE_SCRIPT_POPZONE_);
		POPULATION.set_function("IS_POPZONE_VALID_", LUA_NATIVE_POPULATION_IS_POPZONE_VALID_);
		POPULATION.set_function("SET_POPZONE_POPULATION_SET", LUA_NATIVE_POPULATION_SET_POPZONE_POPULATION_SET);
		POPULATION.set_function("0x7E6BC0B94F5928F0_", LUA_NATIVE_POPULATION_0x7E6BC0B94F5928F0_);
		POPULATION.set_function("0x578E2FA64E847C60_", LUA_NATIVE_POPULATION_0x578E2FA64E847C60_);
		POPULATION.set_function("0x08892122769770D5_", LUA_NATIVE_POPULATION_0x08892122769770D5_);
		POPULATION.set_function("0x0F1861101C9A9944_", LUA_NATIVE_POPULATION_0x0F1861101C9A9944_);
		POPULATION.set_function("SET_SPAWNER_INFO_PRIORITY", LUA_NATIVE_POPULATION_SET_SPAWNER_INFO_PRIORITY);
		POPULATION.set_function("CLEAR_SPAWNER_INFO_PRIORITY", LUA_NATIVE_POPULATION_CLEAR_SPAWNER_INFO_PRIORITY);
		POPULATION.set_function("0x638FCFC6042A9473_", LUA_NATIVE_POPULATION_0x638FCFC6042A9473_);
		POPULATION.set_function("ADD_AMBIENT_AVOIDANCE_RESTRICTION_", LUA_NATIVE_POPULATION_ADD_AMBIENT_AVOIDANCE_RESTRICTION_);
		POPULATION.set_function("REMOVE_AMBIENT_AVOIDANCE_RESTRICTION_", LUA_NATIVE_POPULATION_REMOVE_AMBIENT_AVOIDANCE_RESTRICTION_);
		POPULATION.set_function("ADD_AMBIENT_SPAWN_RESTRICTION_", LUA_NATIVE_POPULATION_ADD_AMBIENT_SPAWN_RESTRICTION_);
		POPULATION.set_function("REMOVE_AMBIENT_SPAWN_RESTRICTION_", LUA_NATIVE_POPULATION_REMOVE_AMBIENT_SPAWN_RESTRICTION_);
		POPULATION.set_function("0x2161278C6322F740_", LUA_NATIVE_POPULATION_0x2161278C6322F740_);
		POPULATION.set_function("0xF45E46DEECF7DF6E_", LUA_NATIVE_POPULATION_0xF45E46DEECF7DF6E_);
		POPULATION.set_function("0x8EC7CD701F872F87_", LUA_NATIVE_POPULATION_0x8EC7CD701F872F87_);
		POPULATION.set_function("0xC4533E3E87125C9E_", LUA_NATIVE_POPULATION_0xC4533E3E87125C9E_);
		POPULATION.set_function("SET_PED_SHOULD_IGNORE_AVOIDANCE_VOLUMES_", LUA_NATIVE_POPULATION_SET_PED_SHOULD_IGNORE_AVOIDANCE_VOLUMES_);
		POPULATION.set_function("0xDBBF12EA7C1029B2_", LUA_NATIVE_POPULATION_0xDBBF12EA7C1029B2_);
		POPULATION.set_function("0x247F86595D396344_", LUA_NATIVE_POPULATION_0x247F86595D396344_);
		POPULATION.set_function("0x324AB2A68AD8AEE5_", LUA_NATIVE_POPULATION_0x324AB2A68AD8AEE5_);
		POPULATION.set_function("DISABLE_AMBIENT_ROAD_POPULATION", LUA_NATIVE_POPULATION_DISABLE_AMBIENT_ROAD_POPULATION);
		POPULATION.set_function("ENABLE_AMBIENT_ROAD_POPULATION", LUA_NATIVE_POPULATION_ENABLE_AMBIENT_ROAD_POPULATION);
		POPULATION.set_function("0x2660E7720EDC4BD0_", LUA_NATIVE_POPULATION_0x2660E7720EDC4BD0_);
		POPULATION.set_function("GET_RANDOM_FISH_TYPE_FOR_LOCATION_", LUA_NATIVE_POPULATION_GET_RANDOM_FISH_TYPE_FOR_LOCATION_);
		POPULATION.set_function("0xEC116EDB683AD479_", LUA_NATIVE_POPULATION_0xEC116EDB683AD479_);
	}
}
