#include "lua_native_binding.hpp"
#include "game/rdr/Natives.hpp"

namespace Lua::native
{
	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_PAY_OFF_BOUNTY_(uintptr_t outRpcGuid)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_REQUEST_PAY_OFF_BOUNTY((Any*)outRpcGuid);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_PAY_OFF_BOUNTY_EX_(uintptr_t outRpcGuid, Hash p1, Hash costType)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_REQUEST_PAY_OFF_BOUNTY_EX((Any*)outRpcGuid, p1, costType);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_SELF_REPORT_CRIME_(uintptr_t outRpcGuid, Hash crimeType, bool p2)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_REQUEST_SELF_REPORT_CRIME((Any*)outRpcGuid, crimeType, p2);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_SELF_REPORT_KILLED_BY_BOUNTY_HUNTER_(uintptr_t outRpcGuid)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_REQUEST_SELF_REPORT_KILLED_BY_BOUNTY_HUNTER((Any*)outRpcGuid);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_GET_BOUNTY_ON_PLAYER(uintptr_t gamerHandle, uintptr_t bountyData)
	{
		auto retval = (bool)BOUNTY::BOUNTY_GET_BOUNTY_ON_PLAYER((Any*)gamerHandle, (Any*)bountyData);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_IS_REQUEST_PENDING_(uintptr_t rpcGuid)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_IS_REQUEST_PENDING((Any*)rpcGuid);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_BEGIN_WANTED_POSTER_(uintptr_t outRpcGuid, int p1)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_REQUEST_BEGIN_WANTED_POSTER((Any*)outRpcGuid, p1);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_0x81847C2134039BDC_(uintptr_t p0)
	{
		auto retval = (bool)BOUNTY::_0x81847C2134039BDC((Any*)p0);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_COMPLETE_WANTED_POSTER_(uintptr_t outRpcGuid, uintptr_t p1)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_REQUEST_COMPLETE_WANTED_POSTER((Any*)outRpcGuid, (Any*)p1);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_COMPLETE_SPLIT_WANTED_POSTER_(uintptr_t outRpcGuid, uintptr_t p1)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_REQUEST_COMPLETE_SPLIT_WANTED_POSTER((Any*)outRpcGuid, (Any*)p1);
		return retval;
	}

	static void LUA_NATIVE_BOUNTY_BOUNTY_CANCEL_WANTED_POSTER_()
	{
		BOUNTY::_BOUNTY_CANCEL_WANTED_POSTER();
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_BEGIN_LEGENDARY_MISSION(uintptr_t outRpcGuid, int p1, int p2)
	{
		auto retval = (bool)BOUNTY::BOUNTY_REQUEST_BEGIN_LEGENDARY_MISSION((Any*)outRpcGuid, p1, p2);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_BEGIN_LEGENDARY_MISSION_FOR_POSSE(uintptr_t outRpcGuid, int p1, int p2)
	{
		auto retval = (bool)BOUNTY::BOUNTY_REQUEST_BEGIN_LEGENDARY_MISSION_FOR_POSSE((Any*)outRpcGuid, p1, p2);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_COMPLETE_LEGENDARY_MISSION_(uintptr_t outRpcGuid, uintptr_t p1)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_REQUEST_COMPLETE_LEGENDARY_MISSION((Any*)outRpcGuid, (Any*)p1);
		return retval;
	}

	static void LUA_NATIVE_BOUNTY_BOUNTY_CANCEL_LEGENDARY_MISSION_()
	{
		BOUNTY::_BOUNTY_CANCEL_LEGENDARY_MISSION();
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_GET_WANTED_POSTER_SLOT(Hash p0, Hash p1, uintptr_t p2)
	{
		auto retval = (bool)BOUNTY::BOUNTY_GET_WANTED_POSTER_SLOT(p0, p1, (Any*)p2);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_GET_LEGENDARY_TARGET(Any p0, uintptr_t p1)
	{
		auto retval = (bool)BOUNTY::BOUNTY_GET_LEGENDARY_TARGET(p0, (Any*)p1);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_0x86EC5F83867C4B70_(uintptr_t p0)
	{
		auto retval = (bool)BOUNTY::_0x86EC5F83867C4B70((Any*)p0);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_GET_COOLDOWN_COLLECTION(uintptr_t p0)
	{
		auto retval = (bool)BOUNTY::BOUNTY_GET_COOLDOWN_COLLECTION((Any*)p0);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_BECOME_TARGET_OF_CHARACTER_BOUNTY_HUNT_(uintptr_t outRpcGuid)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_REQUEST_BECOME_TARGET_OF_CHARACTER_BOUNTY_HUNT((Any*)outRpcGuid);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_0x27D3A0E1FE090A43_(uintptr_t p0)
	{
		auto retval = (bool)BOUNTY::_0x27D3A0E1FE090A43((Any*)p0);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_CLAIM_CHARACTER_BOUNTY_(uintptr_t outRpcGuid, int p1, uintptr_t p2)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_REQUEST_CLAIM_CHARACTER_BOUNTY((Any*)outRpcGuid, p1, (Any*)p2);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_POSSE_LEADER_CLAIM_CHARACTER_BOUNTY_(uintptr_t outRpcGuid, int p1, uintptr_t p2)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_REQUEST_POSSE_LEADER_CLAIM_CHARACTER_BOUNTY((Any*)outRpcGuid, p1, (Any*)p2);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_POSSE_MEMBER_CLAIM_CHARACTER_BOUNTY_SHARE_(uintptr_t outRpcGuid, uintptr_t p1)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_REQUEST_POSSE_MEMBER_CLAIM_CHARACTER_BOUNTY_SHARE((Any*)outRpcGuid, (Any*)p1);
		return retval;
	}

	static void LUA_NATIVE_BOUNTY_BOUNTY_CLEAR_BEING_BOUNTY_HUNTER_()
	{
		BOUNTY::_BOUNTY_CLEAR_BEING_BOUNTY_HUNTER();
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_ESCAPED_CHARACTER_BOUNTY_HUNT_(uintptr_t outRpcGuid)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_REQUEST_ESCAPED_CHARACTER_BOUNTY_HUNT((Any*)outRpcGuid);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_POSSE_LEADER_ESCAPED_CHARACTER_BOUNTY_HUNT_(uintptr_t outRpcGuid)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_REQUEST_POSSE_LEADER_ESCAPED_CHARACTER_BOUNTY_HUNT((Any*)outRpcGuid);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_POSSE_MEMBER_ESCAPED_CHARACTER_BOUNTY_HUNT_(uintptr_t outRpcGuid)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_REQUEST_POSSE_MEMBER_ESCAPED_CHARACTER_BOUNTY_HUNT((Any*)outRpcGuid);
		return retval;
	}

	static void LUA_NATIVE_BOUNTY_BOUNTY_CLEAR_BEING_TARGET_()
	{
		BOUNTY::_BOUNTY_CLEAR_BEING_TARGET();
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_SERVED_FULL_JAIL_SENTENCE_(uintptr_t outRpcGuid)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_REQUEST_SERVED_FULL_JAIL_SENTENCE((Any*)outRpcGuid);
		return retval;
	}

	static bool LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_BRIBE_JAIL_GUARD_(uintptr_t outRpcGuid, int p1)
	{
		auto retval = (bool)BOUNTY::_BOUNTY_REQUEST_BRIBE_JAIL_GUARD((Any*)outRpcGuid, p1);
		return retval;
	}

	static int LUA_NATIVE_BOUNTY_0xF8BCC5ECA33AC9C1_()
	{
		auto retval = BOUNTY::_0xF8BCC5ECA33AC9C1();
		return retval;
	}

	static int LUA_NATIVE_BOUNTY_0xD6A67E2FF373D0E3_(int p0)
	{
		auto retval = BOUNTY::_0xD6A67E2FF373D0E3(p0);
		return retval;
	}

	void init_native_binding_BOUNTY(sol::state& L)
	{
		auto BOUNTY = L["BOUNTY"].get_or_create<sol::table>();
		BOUNTY.set_function("BOUNTY_REQUEST_PAY_OFF_BOUNTY_", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_PAY_OFF_BOUNTY_);
		BOUNTY.set_function("BOUNTY_REQUEST_PAY_OFF_BOUNTY_EX_", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_PAY_OFF_BOUNTY_EX_);
		BOUNTY.set_function("BOUNTY_REQUEST_SELF_REPORT_CRIME_", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_SELF_REPORT_CRIME_);
		BOUNTY.set_function("BOUNTY_REQUEST_SELF_REPORT_KILLED_BY_BOUNTY_HUNTER_", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_SELF_REPORT_KILLED_BY_BOUNTY_HUNTER_);
		BOUNTY.set_function("BOUNTY_GET_BOUNTY_ON_PLAYER", LUA_NATIVE_BOUNTY_BOUNTY_GET_BOUNTY_ON_PLAYER);
		BOUNTY.set_function("BOUNTY_IS_REQUEST_PENDING_", LUA_NATIVE_BOUNTY_BOUNTY_IS_REQUEST_PENDING_);
		BOUNTY.set_function("BOUNTY_REQUEST_BEGIN_WANTED_POSTER_", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_BEGIN_WANTED_POSTER_);
		BOUNTY.set_function("0x81847C2134039BDC_", LUA_NATIVE_BOUNTY_0x81847C2134039BDC_);
		BOUNTY.set_function("BOUNTY_REQUEST_COMPLETE_WANTED_POSTER_", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_COMPLETE_WANTED_POSTER_);
		BOUNTY.set_function("BOUNTY_REQUEST_COMPLETE_SPLIT_WANTED_POSTER_", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_COMPLETE_SPLIT_WANTED_POSTER_);
		BOUNTY.set_function("BOUNTY_CANCEL_WANTED_POSTER_", LUA_NATIVE_BOUNTY_BOUNTY_CANCEL_WANTED_POSTER_);
		BOUNTY.set_function("BOUNTY_REQUEST_BEGIN_LEGENDARY_MISSION", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_BEGIN_LEGENDARY_MISSION);
		BOUNTY.set_function("BOUNTY_REQUEST_BEGIN_LEGENDARY_MISSION_FOR_POSSE", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_BEGIN_LEGENDARY_MISSION_FOR_POSSE);
		BOUNTY.set_function("BOUNTY_REQUEST_COMPLETE_LEGENDARY_MISSION_", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_COMPLETE_LEGENDARY_MISSION_);
		BOUNTY.set_function("BOUNTY_CANCEL_LEGENDARY_MISSION_", LUA_NATIVE_BOUNTY_BOUNTY_CANCEL_LEGENDARY_MISSION_);
		BOUNTY.set_function("BOUNTY_GET_WANTED_POSTER_SLOT", LUA_NATIVE_BOUNTY_BOUNTY_GET_WANTED_POSTER_SLOT);
		BOUNTY.set_function("BOUNTY_GET_LEGENDARY_TARGET", LUA_NATIVE_BOUNTY_BOUNTY_GET_LEGENDARY_TARGET);
		BOUNTY.set_function("0x86EC5F83867C4B70_", LUA_NATIVE_BOUNTY_0x86EC5F83867C4B70_);
		BOUNTY.set_function("BOUNTY_GET_COOLDOWN_COLLECTION", LUA_NATIVE_BOUNTY_BOUNTY_GET_COOLDOWN_COLLECTION);
		BOUNTY.set_function("BOUNTY_REQUEST_BECOME_TARGET_OF_CHARACTER_BOUNTY_HUNT_", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_BECOME_TARGET_OF_CHARACTER_BOUNTY_HUNT_);
		BOUNTY.set_function("0x27D3A0E1FE090A43_", LUA_NATIVE_BOUNTY_0x27D3A0E1FE090A43_);
		BOUNTY.set_function("BOUNTY_REQUEST_CLAIM_CHARACTER_BOUNTY_", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_CLAIM_CHARACTER_BOUNTY_);
		BOUNTY.set_function("BOUNTY_REQUEST_POSSE_LEADER_CLAIM_CHARACTER_BOUNTY_", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_POSSE_LEADER_CLAIM_CHARACTER_BOUNTY_);
		BOUNTY.set_function("BOUNTY_REQUEST_POSSE_MEMBER_CLAIM_CHARACTER_BOUNTY_SHARE_", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_POSSE_MEMBER_CLAIM_CHARACTER_BOUNTY_SHARE_);
		BOUNTY.set_function("BOUNTY_CLEAR_BEING_BOUNTY_HUNTER_", LUA_NATIVE_BOUNTY_BOUNTY_CLEAR_BEING_BOUNTY_HUNTER_);
		BOUNTY.set_function("BOUNTY_REQUEST_ESCAPED_CHARACTER_BOUNTY_HUNT_", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_ESCAPED_CHARACTER_BOUNTY_HUNT_);
		BOUNTY.set_function("BOUNTY_REQUEST_POSSE_LEADER_ESCAPED_CHARACTER_BOUNTY_HUNT_", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_POSSE_LEADER_ESCAPED_CHARACTER_BOUNTY_HUNT_);
		BOUNTY.set_function("BOUNTY_REQUEST_POSSE_MEMBER_ESCAPED_CHARACTER_BOUNTY_HUNT_", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_POSSE_MEMBER_ESCAPED_CHARACTER_BOUNTY_HUNT_);
		BOUNTY.set_function("BOUNTY_CLEAR_BEING_TARGET_", LUA_NATIVE_BOUNTY_BOUNTY_CLEAR_BEING_TARGET_);
		BOUNTY.set_function("BOUNTY_REQUEST_SERVED_FULL_JAIL_SENTENCE_", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_SERVED_FULL_JAIL_SENTENCE_);
		BOUNTY.set_function("BOUNTY_REQUEST_BRIBE_JAIL_GUARD_", LUA_NATIVE_BOUNTY_BOUNTY_REQUEST_BRIBE_JAIL_GUARD_);
		BOUNTY.set_function("0xF8BCC5ECA33AC9C1_", LUA_NATIVE_BOUNTY_0xF8BCC5ECA33AC9C1_);
		BOUNTY.set_function("0xD6A67E2FF373D0E3_", LUA_NATIVE_BOUNTY_0xD6A67E2FF373D0E3_);
	}
}
