#include "lua_native_binding.hpp"
#include "game/rdr/Natives.hpp"

namespace Lua::native
{
	static Any LUA_NATIVE_DATABINDING_DATABINDING_GET_DATA_CONTAINER_FROM_PATH_(sol::stack_object p0)
	{
		auto retval = DATABINDING::_DATABINDING_GET_DATA_CONTAINER_FROM_PATH(p0.is<const char*>() ? p0.as<const char*>() : nullptr);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_GET_DATA_CONTAINER_FROM_CHILD_INDEX_(Hash entryId, int p1)
	{
		auto retval = DATABINDING::_DATABINDING_GET_DATA_CONTAINER_FROM_CHILD_INDEX(entryId, p1);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_0xD7DB94AB78E8EBE4_(sol::stack_object p0, Hash p1)
	{
		auto retval = DATABINDING::_0xD7DB94AB78E8EBE4(p0.is<const char*>() ? p0.as<const char*>() : nullptr, p1);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_CONTAINER_FROM_PATH_(sol::stack_object p0, sol::stack_object p1)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_DATA_CONTAINER_FROM_PATH(p0.is<const char*>() ? p0.as<const char*>() : nullptr, p1.is<const char*>() ? p1.as<const char*>() : nullptr);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_CONTAINER_BY_HASH_(Any p0, Hash p1)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_DATA_CONTAINER_BY_HASH(p0, p1);
		return retval;
	}

	static Hash LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_CONTAINER_(Hash entryId, sol::stack_object p1)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_DATA_CONTAINER(entryId, p1.is<const char*>() ? p1.as<const char*>() : nullptr);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_BOOL_FROM_PATH_(sol::stack_object p0, sol::stack_object p1, bool p2)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_DATA_BOOL_FROM_PATH(p0.is<const char*>() ? p0.as<const char*>() : nullptr, p1.is<const char*>() ? p1.as<const char*>() : nullptr, p2);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_BOOL_BY_HASH_(Any p0, Hash p1, bool p2)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_DATA_BOOL_BY_HASH(p0, p1, p2);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_BOOL_(Any p0, sol::stack_object p1, bool p2)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_DATA_BOOL(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, p2);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_INT_BY_HASH_(Any p0, Hash p1, int p2)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_DATA_INT_BY_HASH(p0, p1, p2);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_INT_(Any p0, sol::stack_object p1, Hash p2)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_DATA_INT(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, p2);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_FLOAT_(Any p0, sol::stack_object p1, float p2)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_DATA_FLOAT(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, p2);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_HASH_BY_HASH_(Any p0, Hash p1, Hash p2)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_DATA_HASH_BY_HASH(p0, p1, p2);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_HASH_(Any p0, sol::stack_object p1, Hash p2)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_DATA_HASH(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, p2);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_STRING_FROM_PATH_(sol::stack_object p0, sol::stack_object p1, sol::stack_object p2)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_DATA_STRING_FROM_PATH(p0.is<const char*>() ? p0.as<const char*>() : nullptr, p1.is<const char*>() ? p1.as<const char*>() : nullptr, p2.is<const char*>() ? p2.as<const char*>() : nullptr);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_STRING_BY_HASH_(Any p0, Hash p1, sol::stack_object p2)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_DATA_STRING_BY_HASH(p0, p1, p2.is<const char*>() ? p2.as<const char*>() : nullptr);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_STRING_(Any p0, sol::stack_object p1, sol::stack_object p2)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_DATA_STRING(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, p2.is<const char*>() ? p2.as<const char*>() : nullptr);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_GANG_ID_(Any p0, sol::stack_object p1, Any gangId)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_DATA_GANG_ID(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, gangId);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_POSSE_ID_(Any p0, sol::stack_object p1, Any posseId)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_DATA_POSSE_ID(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, posseId);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_0x294AF5323F44B053_(Any p0, sol::stack_object p1, Any p2)
	{
		auto retval = DATABINDING::_0x294AF5323F44B053(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, p2);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_UI_ITEM_LIST_FROM_PATH_(sol::stack_object p0, sol::stack_object p1)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_UI_ITEM_LIST_FROM_PATH(p0.is<const char*>() ? p0.as<const char*>() : nullptr, p1.is<const char*>() ? p1.as<const char*>() : nullptr);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_UI_ITEM_LIST_BY_HASH_(Any p0, Hash p1)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_UI_ITEM_LIST_BY_HASH(p0, p1);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_UI_ITEM_LIST_(Any p0, sol::stack_object p1)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_UI_ITEM_LIST(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr);
		return retval;
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS_(Any p0, int index, sol::stack_object p2, Any p3)
	{
		DATABINDING::_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS(p0, index, p2.is<const char*>() ? p2.as<const char*>() : nullptr, p3);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_HASH_ALIAS_(Any p0, int index, Hash p2, Any p3)
	{
		DATABINDING::_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_HASH_ALIAS(p0, index, p2, p3);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_PATH_STRING_ALIAS_(Any p0, Any p1, sol::stack_object p2, Any p3)
	{
		DATABINDING::_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_PATH_STRING_ALIAS(p0, p1, p2.is<const char*>() ? p2.as<const char*>() : nullptr, p3);
	}

	static void LUA_NATIVE_DATABINDING_0x6318FB3BE37E11B3_(Hash entryId, int index)
	{
		DATABINDING::_0x6318FB3BE37E11B3(entryId, index);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_REMOVE_BINDING_ARRAY_ITEM_BY_DATA_CONTEXT_ID_(Any p0, Hash entryId)
	{
		DATABINDING::_DATABINDING_REMOVE_BINDING_ARRAY_ITEM_BY_DATA_CONTEXT_ID(p0, entryId);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_CLEAR_BINDING_ARRAY_(Hash entryId)
	{
		DATABINDING::_DATABINDING_CLEAR_BINDING_ARRAY(entryId);
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_GET_ITEM_CONTEXT_BY_INDEX_(Any p0, int index)
	{
		auto retval = DATABINDING::_DATABINDING_GET_ITEM_CONTEXT_BY_INDEX(p0, index);
		return retval;
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_SET_TEMPLATED_UI_ITEM_LIST_SIZE_(Any p0, int p1)
	{
		DATABINDING::_DATABINDING_SET_TEMPLATED_UI_ITEM_LIST_SIZE(p0, p1);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_SET_TEMPLATED_UI_ITEM_HASH_ALIAS_(Any p0, int p1, Hash p2)
	{
		DATABINDING::_DATABINDING_SET_TEMPLATED_UI_ITEM_HASH_ALIAS(p0, p1, p2);
	}

	static Any LUA_NATIVE_DATABINDING_0xD48993A61938C64D_(Any p0, sol::stack_object p1)
	{
		auto retval = DATABINDING::_0xD48993A61938C64D(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_HASH_ARRAY_(Any p0, sol::stack_object p1)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_HASH_ARRAY(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_ADD_STRING_ARRAY_(Any p0, sol::stack_object p1)
	{
		auto retval = DATABINDING::_DATABINDING_ADD_STRING_ARRAY(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr);
		return retval;
	}

	static void LUA_NATIVE_DATABINDING_0x1919D59E60FD516E_(Any p0, int p1, int p2)
	{
		DATABINDING::_0x1919D59E60FD516E(p0, p1, p2);
	}

	static void LUA_NATIVE_DATABINDING_0x7FC60C94C83C5CD7_(Any p0, Hash p1, int p2)
	{
		DATABINDING::_0x7FC60C94C83C5CD7(p0, p1, p2);
	}

	static void LUA_NATIVE_DATABINDING_0xC900CEC8A172375B_(Any p0, sol::stack_object p1, int p2)
	{
		DATABINDING::_0xC900CEC8A172375B(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, p2);
	}

	static Any LUA_NATIVE_DATABINDING_0x02B21B6BEEDD83CC_(Hash entryId, int p1)
	{
		auto retval = DATABINDING::_0x02B21B6BEEDD83CC(entryId, p1);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_0xF47E33F8D2523825_(Any p0, int p1)
	{
		auto retval = DATABINDING::_0xF47E33F8D2523825(p0, p1);
		return retval;
	}

	static void LUA_NATIVE_DATABINDING_0x3BF0767CF33FCC88_(Hash entryId)
	{
		DATABINDING::_0x3BF0767CF33FCC88(entryId);
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_GET_ARRAY_COUNT_(Hash entryId)
	{
		auto retval = DATABINDING::_DATABINDING_GET_ARRAY_COUNT(entryId);
		return retval;
	}

	template <typename... Args>
	static void LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_SCRIPT_VARIABLES_(int p0, int p1, Args&&... varargs)
	{
		DATABINDING::_DATABINDING_WRITE_DATA_SCRIPT_VARIABLES(p0, p1, varargs);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_BOOL_(Any p0, bool p1)
	{
		DATABINDING::_DATABINDING_WRITE_DATA_BOOL(p0, p1);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_BOOL_FROM_PARENT_(Any p0, sol::stack_object p1, bool p2)
	{
		DATABINDING::_DATABINDING_WRITE_DATA_BOOL_FROM_PARENT(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, p2);
	}

	static void LUA_NATIVE_DATABINDING_0xBFC83DA249BEFCC9_(Any p0, Hash p1, Any p2)
	{
		DATABINDING::_0xBFC83DA249BEFCC9(p0, p1, p2);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_INT_(Any p0, int p1)
	{
		DATABINDING::_DATABINDING_WRITE_DATA_INT(p0, p1);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_INT_FROM_PARENT_(Any p0, sol::stack_object p1, int p2)
	{
		DATABINDING::_DATABINDING_WRITE_DATA_INT_FROM_PARENT(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, p2);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_INT_FROM_PARENT_BY_HASH_(Any p0, Hash p1, Any p2)
	{
		DATABINDING::_DATABINDING_WRITE_DATA_INT_FROM_PARENT_BY_HASH(p0, p1, p2);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_FLOAT_(Any p0, float p1)
	{
		DATABINDING::_DATABINDING_WRITE_DATA_FLOAT(p0, p1);
	}

	static void LUA_NATIVE_DATABINDING_0x05AC9E1E02975AFB_(Any p0, sol::stack_object p1, float p2)
	{
		DATABINDING::_0x05AC9E1E02975AFB(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, p2);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_HASH_STRING_(Any p0, Hash p1)
	{
		DATABINDING::_DATABINDING_WRITE_DATA_HASH_STRING(p0, p1);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_HASH_STRING_FROM_PARENT_(Any p0, sol::stack_object p1, Hash p2)
	{
		DATABINDING::_DATABINDING_WRITE_DATA_HASH_STRING_FROM_PARENT(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, p2);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_HASH_STRING_FROM_PARENT_BY_HASH_(Any p0, Hash p1, Any p2)
	{
		DATABINDING::_DATABINDING_WRITE_DATA_HASH_STRING_FROM_PARENT_BY_HASH(p0, p1, p2);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_STRING_(Any p0, sol::stack_object p1)
	{
		DATABINDING::_DATABINDING_WRITE_DATA_STRING(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_WRITE_STRING_FROM_PARENT(Any p0, sol::stack_object p1, sol::stack_object p2)
	{
		DATABINDING::DATABINDING_WRITE_STRING_FROM_PARENT(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, p2.is<const char*>() ? p2.as<const char*>() : nullptr);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_WRITE_STRING_FROM_HASH_(Any p0, Hash p1, sol::stack_object p2)
	{
		DATABINDING::_DATABINDING_WRITE_STRING_FROM_HASH(p0, p1, p2.is<const char*>() ? p2.as<const char*>() : nullptr);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_GANG_ID_(Any p0, sol::stack_object p1, Any gangId)
	{
		DATABINDING::_DATABINDING_WRITE_DATA_GANG_ID(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, gangId);
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_POSSE_ID_(Any p0, sol::stack_object p1, Any posseId)
	{
		DATABINDING::_DATABINDING_WRITE_DATA_POSSE_ID(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, posseId);
	}

	static void LUA_NATIVE_DATABINDING_0x422179C7F6AD9304_(Any p0, uintptr_t gamerHandle)
	{
		DATABINDING::_0x422179C7F6AD9304(p0, (Any*)gamerHandle);
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_BOOL_(Any p0)
	{
		auto retval = DATABINDING::_DATABINDING_READ_DATA_BOOL(p0);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_BOOL_FROM_PARENT_(Any p0, sol::stack_object p1)
	{
		auto retval = DATABINDING::_DATABINDING_READ_DATA_BOOL_FROM_PARENT(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_BOOL_FROM_PARENT_BY_HASH_(Any p0, Hash p1)
	{
		auto retval = DATABINDING::_DATABINDING_READ_DATA_BOOL_FROM_PARENT_BY_HASH(p0, p1);
		return retval;
	}

	static int LUA_NATIVE_DATABINDING_DATABINDING_READ_INT(Any p0)
	{
		auto retval = DATABINDING::DATABINDING_READ_INT(p0);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_INT_FROM_PARENT_(Any p0, sol::stack_object p1)
	{
		auto retval = DATABINDING::_DATABINDING_READ_DATA_INT_FROM_PARENT(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_INT_FROM_PARENT_BY_HASH_(Any p0, Hash p1)
	{
		auto retval = DATABINDING::_DATABINDING_READ_DATA_INT_FROM_PARENT_BY_HASH(p0, p1);
		return retval;
	}

	static float LUA_NATIVE_DATABINDING_DATABINDING_READ_FLOAT_(Hash entryId)
	{
		auto retval = DATABINDING::_DATABINDING_READ_FLOAT(entryId);
		return retval;
	}

	static Hash LUA_NATIVE_DATABINDING_DATABINDING_READ_HASH_(Hash entryId)
	{
		auto retval = DATABINDING::_DATABINDING_READ_HASH(entryId);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_HASH_STRING_FROM_PARENT_(Any p0, sol::stack_object p1)
	{
		auto retval = DATABINDING::_DATABINDING_READ_DATA_HASH_STRING_FROM_PARENT(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_HASH_STRING_FROM_PARENT_BY_HASH_(Any p0, Hash p1)
	{
		auto retval = DATABINDING::_DATABINDING_READ_DATA_HASH_STRING_FROM_PARENT_BY_HASH(p0, p1);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_STRING_(Any p0)
	{
		auto retval = DATABINDING::_DATABINDING_READ_DATA_STRING(p0);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_STRING_FROM_PARENT_(Any p0, sol::stack_object p1)
	{
		auto retval = DATABINDING::_DATABINDING_READ_DATA_STRING_FROM_PARENT(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_0x6329C34BEE5BFF4B_(Any p0, Hash p1)
	{
		auto retval = DATABINDING::_0x6329C34BEE5BFF4B(p0, p1);
		return retval;
	}

	static Any LUA_NATIVE_DATABINDING_0xE6AAB897120492D6_(Any p0, sol::stack_object p1)
	{
		auto retval = DATABINDING::_0xE6AAB897120492D6(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr);
		return retval;
	}

	static void LUA_NATIVE_DATABINDING_0xE6AAB897120492D7_(Any p0, sol::stack_object p1, Any p2)
	{
		DATABINDING::_0xE6AAB897120492D7(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, p2);
	}

	static void LUA_NATIVE_DATABINDING_0xB138CA787F3DD858_(Any p0, sol::stack_object p1, Any p2)
	{
		DATABINDING::_0xB138CA787F3DD858(p0, p1.is<const char*>() ? p1.as<const char*>() : nullptr, p2);
	}

	static bool LUA_NATIVE_DATABINDING_DATABINDING_IS_ENTRY_VALID(Hash entryId)
	{
		auto retval = (bool)DATABINDING::DATABINDING_IS_ENTRY_VALID(entryId);
		return retval;
	}

	static void LUA_NATIVE_DATABINDING_DATABINDING_REMOVE_DATA_ENTRY_(Hash entryId)
	{
		DATABINDING::_DATABINDING_REMOVE_DATA_ENTRY(entryId);
	}

	static void LUA_NATIVE_DATABINDING_VIRTUAL_COLLECTION_SET_SIZE_(Any p0, int size)
	{
		DATABINDING::_VIRTUAL_COLLECTION_SET_SIZE(p0, size);
	}

	static void LUA_NATIVE_DATABINDING_VIRTUAL_COLLECTION_SET_INTEREST_INDEX_(Any p0, int interestIndex)
	{
		DATABINDING::_VIRTUAL_COLLECTION_SET_INTEREST_INDEX(p0, interestIndex);
	}

	static void LUA_NATIVE_DATABINDING_VIRTUAL_COLLECTION_ITEM_ADD_(Any p0, int index, Hash p2, Any p3)
	{
		DATABINDING::_VIRTUAL_COLLECTION_ITEM_ADD(p0, index, p2, p3);
	}

	static void LUA_NATIVE_DATABINDING_VIRTUAL_COLLECTION_RESET_(Any p0)
	{
		DATABINDING::_VIRTUAL_COLLECTION_RESET(p0);
	}

	static Any LUA_NATIVE_DATABINDING_VIRTUAL_COLLECTION_EXISTS_(Any p0)
	{
		auto retval = DATABINDING::_VIRTUAL_COLLECTION_EXISTS(p0);
		return retval;
	}

	void init_native_binding_DATABINDING(sol::state& L)
	{
		auto DATABINDING = L["DATABINDING"].get_or_create<sol::table>();
		DATABINDING.set_function("DATABINDING_GET_DATA_CONTAINER_FROM_PATH_", LUA_NATIVE_DATABINDING_DATABINDING_GET_DATA_CONTAINER_FROM_PATH_);
		DATABINDING.set_function("DATABINDING_GET_DATA_CONTAINER_FROM_CHILD_INDEX_", LUA_NATIVE_DATABINDING_DATABINDING_GET_DATA_CONTAINER_FROM_CHILD_INDEX_);
		DATABINDING.set_function("0xD7DB94AB78E8EBE4_", LUA_NATIVE_DATABINDING_0xD7DB94AB78E8EBE4_);
		DATABINDING.set_function("DATABINDING_ADD_DATA_CONTAINER_FROM_PATH_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_CONTAINER_FROM_PATH_);
		DATABINDING.set_function("DATABINDING_ADD_DATA_CONTAINER_BY_HASH_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_CONTAINER_BY_HASH_);
		DATABINDING.set_function("DATABINDING_ADD_DATA_CONTAINER_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_CONTAINER_);
		DATABINDING.set_function("DATABINDING_ADD_DATA_BOOL_FROM_PATH_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_BOOL_FROM_PATH_);
		DATABINDING.set_function("DATABINDING_ADD_DATA_BOOL_BY_HASH_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_BOOL_BY_HASH_);
		DATABINDING.set_function("DATABINDING_ADD_DATA_BOOL_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_BOOL_);
		DATABINDING.set_function("DATABINDING_ADD_DATA_INT_BY_HASH_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_INT_BY_HASH_);
		DATABINDING.set_function("DATABINDING_ADD_DATA_INT_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_INT_);
		DATABINDING.set_function("DATABINDING_ADD_DATA_FLOAT_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_FLOAT_);
		DATABINDING.set_function("DATABINDING_ADD_DATA_HASH_BY_HASH_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_HASH_BY_HASH_);
		DATABINDING.set_function("DATABINDING_ADD_DATA_HASH_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_HASH_);
		DATABINDING.set_function("DATABINDING_ADD_DATA_STRING_FROM_PATH_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_STRING_FROM_PATH_);
		DATABINDING.set_function("DATABINDING_ADD_DATA_STRING_BY_HASH_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_STRING_BY_HASH_);
		DATABINDING.set_function("DATABINDING_ADD_DATA_STRING_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_STRING_);
		DATABINDING.set_function("DATABINDING_ADD_DATA_GANG_ID_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_GANG_ID_);
		DATABINDING.set_function("DATABINDING_ADD_DATA_POSSE_ID_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_DATA_POSSE_ID_);
		DATABINDING.set_function("0x294AF5323F44B053_", LUA_NATIVE_DATABINDING_0x294AF5323F44B053_);
		DATABINDING.set_function("DATABINDING_ADD_UI_ITEM_LIST_FROM_PATH_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_UI_ITEM_LIST_FROM_PATH_);
		DATABINDING.set_function("DATABINDING_ADD_UI_ITEM_LIST_BY_HASH_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_UI_ITEM_LIST_BY_HASH_);
		DATABINDING.set_function("DATABINDING_ADD_UI_ITEM_LIST_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_UI_ITEM_LIST_);
		DATABINDING.set_function("DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS_", LUA_NATIVE_DATABINDING_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS_);
		DATABINDING.set_function("DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_HASH_ALIAS_", LUA_NATIVE_DATABINDING_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_HASH_ALIAS_);
		DATABINDING.set_function("DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_PATH_STRING_ALIAS_", LUA_NATIVE_DATABINDING_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_PATH_STRING_ALIAS_);
		DATABINDING.set_function("0x6318FB3BE37E11B3_", LUA_NATIVE_DATABINDING_0x6318FB3BE37E11B3_);
		DATABINDING.set_function("DATABINDING_REMOVE_BINDING_ARRAY_ITEM_BY_DATA_CONTEXT_ID_", LUA_NATIVE_DATABINDING_DATABINDING_REMOVE_BINDING_ARRAY_ITEM_BY_DATA_CONTEXT_ID_);
		DATABINDING.set_function("DATABINDING_CLEAR_BINDING_ARRAY_", LUA_NATIVE_DATABINDING_DATABINDING_CLEAR_BINDING_ARRAY_);
		DATABINDING.set_function("DATABINDING_GET_ITEM_CONTEXT_BY_INDEX_", LUA_NATIVE_DATABINDING_DATABINDING_GET_ITEM_CONTEXT_BY_INDEX_);
		DATABINDING.set_function("DATABINDING_SET_TEMPLATED_UI_ITEM_LIST_SIZE_", LUA_NATIVE_DATABINDING_DATABINDING_SET_TEMPLATED_UI_ITEM_LIST_SIZE_);
		DATABINDING.set_function("DATABINDING_SET_TEMPLATED_UI_ITEM_HASH_ALIAS_", LUA_NATIVE_DATABINDING_DATABINDING_SET_TEMPLATED_UI_ITEM_HASH_ALIAS_);
		DATABINDING.set_function("0xD48993A61938C64D_", LUA_NATIVE_DATABINDING_0xD48993A61938C64D_);
		DATABINDING.set_function("DATABINDING_ADD_HASH_ARRAY_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_HASH_ARRAY_);
		DATABINDING.set_function("DATABINDING_ADD_STRING_ARRAY_", LUA_NATIVE_DATABINDING_DATABINDING_ADD_STRING_ARRAY_);
		DATABINDING.set_function("0x1919D59E60FD516E_", LUA_NATIVE_DATABINDING_0x1919D59E60FD516E_);
		DATABINDING.set_function("0x7FC60C94C83C5CD7_", LUA_NATIVE_DATABINDING_0x7FC60C94C83C5CD7_);
		DATABINDING.set_function("0xC900CEC8A172375B_", LUA_NATIVE_DATABINDING_0xC900CEC8A172375B_);
		DATABINDING.set_function("0x02B21B6BEEDD83CC_", LUA_NATIVE_DATABINDING_0x02B21B6BEEDD83CC_);
		DATABINDING.set_function("0xF47E33F8D2523825_", LUA_NATIVE_DATABINDING_0xF47E33F8D2523825_);
		DATABINDING.set_function("0x3BF0767CF33FCC88_", LUA_NATIVE_DATABINDING_0x3BF0767CF33FCC88_);
		DATABINDING.set_function("DATABINDING_GET_ARRAY_COUNT_", LUA_NATIVE_DATABINDING_DATABINDING_GET_ARRAY_COUNT_);
		// DATABINDING.set_function("DATABINDING_WRITE_DATA_SCRIPT_VARIABLES_", LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_SCRIPT_VARIABLES_);
		DATABINDING.set_function("DATABINDING_WRITE_DATA_BOOL_", LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_BOOL_);
		DATABINDING.set_function("DATABINDING_WRITE_DATA_BOOL_FROM_PARENT_", LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_BOOL_FROM_PARENT_);
		DATABINDING.set_function("0xBFC83DA249BEFCC9_", LUA_NATIVE_DATABINDING_0xBFC83DA249BEFCC9_);
		DATABINDING.set_function("DATABINDING_WRITE_DATA_INT_", LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_INT_);
		DATABINDING.set_function("DATABINDING_WRITE_DATA_INT_FROM_PARENT_", LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_INT_FROM_PARENT_);
		DATABINDING.set_function("DATABINDING_WRITE_DATA_INT_FROM_PARENT_BY_HASH_", LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_INT_FROM_PARENT_BY_HASH_);
		DATABINDING.set_function("DATABINDING_WRITE_DATA_FLOAT_", LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_FLOAT_);
		DATABINDING.set_function("0x05AC9E1E02975AFB_", LUA_NATIVE_DATABINDING_0x05AC9E1E02975AFB_);
		DATABINDING.set_function("DATABINDING_WRITE_DATA_HASH_STRING_", LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_HASH_STRING_);
		DATABINDING.set_function("DATABINDING_WRITE_DATA_HASH_STRING_FROM_PARENT_", LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_HASH_STRING_FROM_PARENT_);
		DATABINDING.set_function("DATABINDING_WRITE_DATA_HASH_STRING_FROM_PARENT_BY_HASH_", LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_HASH_STRING_FROM_PARENT_BY_HASH_);
		DATABINDING.set_function("DATABINDING_WRITE_DATA_STRING_", LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_STRING_);
		DATABINDING.set_function("DATABINDING_WRITE_STRING_FROM_PARENT", LUA_NATIVE_DATABINDING_DATABINDING_WRITE_STRING_FROM_PARENT);
		DATABINDING.set_function("DATABINDING_WRITE_STRING_FROM_HASH_", LUA_NATIVE_DATABINDING_DATABINDING_WRITE_STRING_FROM_HASH_);
		DATABINDING.set_function("DATABINDING_WRITE_DATA_GANG_ID_", LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_GANG_ID_);
		DATABINDING.set_function("DATABINDING_WRITE_DATA_POSSE_ID_", LUA_NATIVE_DATABINDING_DATABINDING_WRITE_DATA_POSSE_ID_);
		DATABINDING.set_function("0x422179C7F6AD9304_", LUA_NATIVE_DATABINDING_0x422179C7F6AD9304_);
		DATABINDING.set_function("DATABINDING_READ_DATA_BOOL_", LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_BOOL_);
		DATABINDING.set_function("DATABINDING_READ_DATA_BOOL_FROM_PARENT_", LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_BOOL_FROM_PARENT_);
		DATABINDING.set_function("DATABINDING_READ_DATA_BOOL_FROM_PARENT_BY_HASH_", LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_BOOL_FROM_PARENT_BY_HASH_);
		DATABINDING.set_function("DATABINDING_READ_INT", LUA_NATIVE_DATABINDING_DATABINDING_READ_INT);
		DATABINDING.set_function("DATABINDING_READ_DATA_INT_FROM_PARENT_", LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_INT_FROM_PARENT_);
		DATABINDING.set_function("DATABINDING_READ_DATA_INT_FROM_PARENT_BY_HASH_", LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_INT_FROM_PARENT_BY_HASH_);
		DATABINDING.set_function("DATABINDING_READ_FLOAT_", LUA_NATIVE_DATABINDING_DATABINDING_READ_FLOAT_);
		DATABINDING.set_function("DATABINDING_READ_HASH_", LUA_NATIVE_DATABINDING_DATABINDING_READ_HASH_);
		DATABINDING.set_function("DATABINDING_READ_DATA_HASH_STRING_FROM_PARENT_", LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_HASH_STRING_FROM_PARENT_);
		DATABINDING.set_function("DATABINDING_READ_DATA_HASH_STRING_FROM_PARENT_BY_HASH_", LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_HASH_STRING_FROM_PARENT_BY_HASH_);
		DATABINDING.set_function("DATABINDING_READ_DATA_STRING_", LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_STRING_);
		DATABINDING.set_function("DATABINDING_READ_DATA_STRING_FROM_PARENT_", LUA_NATIVE_DATABINDING_DATABINDING_READ_DATA_STRING_FROM_PARENT_);
		DATABINDING.set_function("0x6329C34BEE5BFF4B_", LUA_NATIVE_DATABINDING_0x6329C34BEE5BFF4B_);
		DATABINDING.set_function("0xE6AAB897120492D6_", LUA_NATIVE_DATABINDING_0xE6AAB897120492D6_);
		DATABINDING.set_function("0xE6AAB897120492D7_", LUA_NATIVE_DATABINDING_0xE6AAB897120492D7_);
		DATABINDING.set_function("0xB138CA787F3DD858_", LUA_NATIVE_DATABINDING_0xB138CA787F3DD858_);
		DATABINDING.set_function("DATABINDING_IS_ENTRY_VALID", LUA_NATIVE_DATABINDING_DATABINDING_IS_ENTRY_VALID);
		DATABINDING.set_function("DATABINDING_REMOVE_DATA_ENTRY_", LUA_NATIVE_DATABINDING_DATABINDING_REMOVE_DATA_ENTRY_);
		DATABINDING.set_function("VIRTUAL_COLLECTION_SET_SIZE_", LUA_NATIVE_DATABINDING_VIRTUAL_COLLECTION_SET_SIZE_);
		DATABINDING.set_function("VIRTUAL_COLLECTION_SET_INTEREST_INDEX_", LUA_NATIVE_DATABINDING_VIRTUAL_COLLECTION_SET_INTEREST_INDEX_);
		DATABINDING.set_function("VIRTUAL_COLLECTION_ITEM_ADD_", LUA_NATIVE_DATABINDING_VIRTUAL_COLLECTION_ITEM_ADD_);
		DATABINDING.set_function("VIRTUAL_COLLECTION_RESET_", LUA_NATIVE_DATABINDING_VIRTUAL_COLLECTION_RESET_);
		DATABINDING.set_function("VIRTUAL_COLLECTION_EXISTS_", LUA_NATIVE_DATABINDING_VIRTUAL_COLLECTION_EXISTS_);
	}
}
